//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentSystemCertificate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificateCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public certificateCategory()
        {
            this.certificateType = new HashSet<certificateType>();
        }
    
        public int id { get; set; }
        public string CertificateCategory1 { get; set; }
        public Nullable<System.DateTime> createat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<certificateType> certificateType { get; set; }
    }
}
