//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentSystemCertificate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CertificateRequest()
        {
            this.Certificate = new HashSet<Certificate>();
        }
    
        public int id { get; set; }
        public string RequestStatus { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> idCitizens { get; set; }
        public Nullable<int> idCertificateType { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificate> Certificate { get; set; }
        public virtual certificateType certificateType { get; set; }
        public virtual Citizen Citizen { get; set; }
    }
}
