//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentSystemCertificate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagementCertificateEntities : DbContext
    {
        public ManagementCertificateEntities()
            : base("name=ManagementCertificateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certificate> Certificate { get; set; }
        public virtual DbSet<certificateCategory> certificateCategory { get; set; }
        public virtual DbSet<CertificateRequest> CertificateRequest { get; set; }
        public virtual DbSet<certificateType> certificateType { get; set; }
        public virtual DbSet<Citizen> Citizen { get; set; }
        public virtual DbSet<Employes> Employes { get; set; }
    }
}
