//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentSystemCertificate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date_delivery { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> idRequest { get; set; }
    
        public virtual CertificateRequest CertificateRequest { get; set; }
    }
}
