//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentSystemCertificate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employes
    {
        public int id { get; set; }
        public string Nationalid { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> createat { get; set; }
        public Nullable<System.DateTime> updateat { get; set; }
        public string Role { get; set; }
        public string Passwords { get; set; }
    }
}
